// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateRead } from './DateRead';

export type AttrValue =
  | { type: 'String'; value: string | null }
  | { type: 'StringVec'; value: Array<string> | null }
  | { type: 'DateReadVec'; value: Array<DateRead> | null }
  | { type: 'Integer'; value: number | null }
  | { type: 'Float'; value: number | null };
