// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingsTypeDate } from './SettingsTypeDate';

export type DateSettings = { settingsType: SettingsTypeDate; displayName?: string };
