// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingsTypeDatesPairCollection } from './SettingsTypeDatesPairCollection';

export type DatesPairCollectionSettings = {
  settingsType: SettingsTypeDatesPairCollection;
  displayName?: string;
};
