// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrFRActionCode } from "./ErrFRActionCode";

export type ErrFR = { isError: boolean, title: string, info?: string, rawError?: string, subErrors: Array<ErrFR>, actionCode?: ErrFRActionCode, actionLabel?: string, };
