// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordFromDb } from './RecordFromDb';
import type { SchemaLocation } from './SchemaLocation';

export type FileEventDataExisting = { path: string; record: RecordFromDb; schema: SchemaLocation };
