// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BreadcrumbItem } from './BreadcrumbItem';

export type FileBreadCrumbs = {
  start: Array<BreadcrumbItem>;
  middle: Array<BreadcrumbItem>;
  end: Array<BreadcrumbItem>;
};
