// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FolderOnDisk = {
  path: string;
  path_relative: string;
  name: string;
  has_schema: boolean;
  own_schema: boolean;
  schema_file_path: string;
};
