// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingsTypeImage } from "./SettingsTypeImage";

export type ImageSettings = { settingsType: SettingsTypeImage, displayName?: string, aspectRatio?: string, };
