// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrFR } from './ErrFR';
import type { FolderEventEmit } from './FolderEventEmit';
import type { RecordFromDb } from './RecordFromDb';
import type { Schema } from './Schema';

export type IPCEmitEvent =
  | { type: 'FileRemove'; data: string }
  | { type: 'FileAdd'; data: RecordFromDb }
  | { type: 'FileUpdate'; data: RecordFromDb }
  | { type: 'FolderRemove'; data: FolderEventEmit }
  | { type: 'FolderAdd'; data: FolderEventEmit }
  | { type: 'ErrorHappened'; data: ErrFR }
  | { type: 'SchemasUpdated'; data: { [key in string]?: Schema } }
  | { type: 'SchemaUpdated'; data: Schema };
