// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrFR } from './ErrFR';
import type { FileEventDataExisting } from './FileEventDataExisting';
import type { FileEventDataRemoved } from './FileEventDataRemoved';
import type { FolderEventData } from './FolderEventData';
import type { Schema } from './Schema';

export type IPCEmitEvent =
  | { type: 'FileRemove'; data: FileEventDataRemoved }
  | { type: 'FileAdd'; data: FileEventDataExisting }
  | { type: 'FileUpdate'; data: FileEventDataExisting }
  | { type: 'FolderRemove'; data: FolderEventData }
  | { type: 'FolderAdd'; data: FolderEventData }
  | { type: 'ErrorHappened'; data: ErrFR }
  | { type: 'SchemasUpdated'; data: { [key in string]?: Schema } }
  | { type: 'EventOverflow'; data: number };
