// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrFR } from './ErrFR';
import type { FolderListGetResult } from './FolderListGetResult';
import type { RecordListGetResult } from './RecordListGetResult';
import type { RecordReadResult } from './RecordReadResult';
import type { RecordSaveResult } from './RecordSaveResult';
import type { Schema } from './Schema';
import type { SchemaResult } from './SchemaResult';

export type IPCResponces = {
  c_init: { Ok: string | null } | { Err: ErrFR };
  c_get_root_path: { Ok: string | null } | { Err: ErrFR };
  c_get_files_path: { Ok: RecordListGetResult } | { Err: ErrFR };
  c_get_all_tags: { Ok: Array<string> } | { Err: ErrFR };
  c_get_all_folders: { Ok: FolderListGetResult } | { Err: ErrFR };
  c_get_all_folders_by_schema: { Ok: FolderListGetResult } | { Err: ErrFR };
  c_read_file_by_path: { Ok: RecordReadResult } | { Err: ErrFR };
  c_get_schemas_usable: { Ok: { [key in string]?: Schema } } | { Err: ErrFR };
  c_get_schemas_all: { Ok: { [key in string]?: Schema } } | { Err: ErrFR };
  c_load_schema: { Ok: Schema } | { Err: ErrFR };
  c_save_schema: { Ok: Schema } | { Err: ErrFR };
  c_save_file: { Ok: RecordSaveResult } | { Err: ErrFR };
  c_resolve_schema_path: { Ok: SchemaResult | null } | { Err: ErrFR };
  c_delete_to_trash: { Ok: null } | { Err: ErrFR };
};
