// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileBreadCrumbs } from './FileBreadCrumbs';
import type { RecordReadResult } from './RecordReadResult';

export type IPCReadFileByPathResult = {
  record: RecordReadResult;
  breadcrumb_items: FileBreadCrumbs;
};
