// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordFromDb } from './RecordFromDb';
import type { SchemaResult } from './SchemaResult';

export type RecordListGetResult = { schema: SchemaResult; records: Array<RecordFromDb> };
