// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordFromDb } from "./RecordFromDb";
import type { Schema } from "./Schema";

export type RecordListGetResult = { schema: Schema, records: Array<RecordFromDb>, };
