// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrFR } from './ErrFR';
import type { RecordFromDb } from './RecordFromDb';
import type { SchemaResult } from './SchemaResult';

export type RecordReadResult = {
  record: RecordFromDb;
  parsing_error: ErrFR | null;
  schema: SchemaResult;
};
