// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrFR } from "./ErrFR";
import type { Schema } from "./Schema";

export type SchemaLoadList = { schemas: { [key in string]?: Schema }, error: ErrFR | null, };
