// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Schema } from './Schema';
import type { SchemaLocation } from './SchemaLocation';

export type SchemaResult = { schema: Schema; location: SchemaLocation };
