// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateCollectionSettings } from './DateCollectionSettings';
import type { DateSettings } from './DateSettings';
import type { DatesPairCollectionSettings } from './DatesPairCollectionSettings';
import type { ImageSettings } from './ImageSettings';
import type { NumberSettings } from './NumberSettings';
import type { TextCollectionSettings } from './TextCollectionSettings';
import type { TextSettings } from './TextSettings';

export type SchemaAttrType =
  | { type: 'Text'; settings: TextSettings }
  | { type: 'TextCollection'; settings: TextCollectionSettings }
  | { type: 'Number'; settings: NumberSettings }
  | { type: 'Date'; settings: DateSettings }
  | { type: 'DateCollection'; settings: DateCollectionSettings }
  | { type: 'DatesPairCollection'; settings: DatesPairCollectionSettings }
  | { type: 'Image'; settings: ImageSettings };
