// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SchemaItem } from './SchemaItem';

export type Schema = {
  name: string;
  version: string;
  fill_from_filename?: string;
  fill_api_search_from?: string;
  items: Array<SchemaItem>;
};
